### ISSUE TITLE
Can't define defaults values or options

### ISSUE THREAD

**Issue by Lelectrolux** [bluora/laravel-model-json-column#8]
When using your package i get this error :
> App\Models\Partner and ModelJsonColumn\JsonColumnTrait define the same property ($json_defaults) in the composition of App\Models\Partner. However, the definition differs and is considered incompatible. Class was composed

By the [documentation](http://php.net/manual/en/language.oop5.traits.php), if you want people to edit their $json_defaults and $json_options properties, you can't define them in traits.

**Comment by therocis** [comment]
Thanks. I've updated this and posted a new release.
